# VM Ãºnica dedicada ao ambiente de desenvolvimento.
# Ajuste vmid, template e storage de acordo com o seu ambiente.
proxmox_api_host: "192.168.100.2"
proxmox_validate_certs: false

proxmox_vms:
  - name: dev-server
    vmid: 200
    node: homelab
    template: TEMPLATE-UBT-SERVER #todo correigir template
    cores: 2
    memory_mb: 1024
    disk_gb: 20
    net0: "virtio,bridge=vmbr0"
    tags: "dev"
    description: "Ambiente de desenvolvimento (app + db)"
